### ISSUE TITLE
Feature request: Make Coffee optional

### ISSUE THREAD

**Issue by timmywil** [yeoman/generator-webapp_DEPRECATED#102]
Rather than creating another generator, it seems to me that this generator could make the inclusion of coffeescript and its dependencies optional, as not everyone who develops web apps likes using it. Actual usage is obviously already optional, but it would be nice not to have to manually delete everything having to do with coffeescript after using the generator.

**Comment by sindresorhus** [comment]
It's completely transparent and you don't have to delete anything, but yes, I do see the point of having a clean gruntfile with only what you need. We chose not to do a prompt for it early on since we didn't want to have so many prompts.

**Comment by timmywil** [comment]
Besides cleaning up the Gruntfile, there's the removal of grunt-contrib-coffee and the 2 hello.coffee's. I agree this does not affect the application, but it does affect the development process. Has the idea of command line options already been rejected? It could be helpful in cases like this where another prompt seems like too much.

``` js
yo webapp --no-coffee
```

**Comment by sindresorhus** [comment]
A `--coffee` flag sounds sensible, though we're working on a prompt systems that remembers your preferences between each invocation, which would make a prompt no big deal. A flag first is probably the quickest fix.

**Comment by oskarrough** [comment]
A first-time user would prefer to use prompts rather than flags.
If you know what you are doing and are setting the flags, perhaps the prompts could be disabled?

That being said, I second making Coffee optional.

**Comment by addyosmani** [comment]
I third Coffee optional as well as Compass. Many of us feel the current webapp generator comes with quite a lot you don't necessarily need.

We're going to look at this further after Yeoman 1.0 is released (soon).

**Comment by addyosmani** [comment]
@stephenplusplus @sindresorhus @passy as we now have 1.0 behind us, I'd like us to figure out whether we would like to move coffee support to a flag or a prompt :)

My personal preference is flag until we have the learning in place, landing before 1.1.

**Comment by sindresorhus** [comment]
@addyosmani agree

**Comment by stephenplusplus** [comment]
Agree with the flag.

**Comment by stephenplusplus** [comment]
(@sindresorhus being "the flag")

**Comment by kevva** [comment]
+1 for ze flag.

**Comment by passy** [comment]
plus eins for ze flag. :de:

**Comment by timmywil** [comment]
![chuck norris says yes](http://blogs.luc.edu/artsalive/files/2013/08/chuck-norris-thumbs-up.jpg)

**Comment by robwierzbowski** [comment]
Side note:

If you want an example of what a verbose prompt can be like, take a look at generator-jekyllrb. Because it scaffolds a website building application, and opinions on structuring a website vary a lot more than, say, structuring an angular or ember app, I gave users more choice.

![screen shot 2013-09-07 at 4 18 16 pm](https://f.cloud.github.com/assets/925735/1102084/adda6d2c-17fa-11e3-96ec-32d0eb5fb5d1.png)

I'm planning on building a dev-environment-and-build-only-generator that supplies tools and build process without templates following a similar structure. Also playing with if it's possible/beneficial to have it as a "peer generator" of another more specific generator, then deep merge the grunt config objects.

**Comment by sindresorhus** [comment]
@robwierzbowski nice! that's definitely where we want to be. any help to get there faster welcome :)

**Comment by robwierzbowski** [comment]
Happy to help! I have an eye on https://github.com/yeoman/generator/issues/277, once the learning prompt is in I'll code up a PR.

**Comment by pankajparashar-zz** [comment]
@robwierzbowski Nice! Personally I prefer the PROMPT approach more than the FLAG approach because the former doesn't need any prior knowledge of optional arguments before you setup the development environment.

The FLAG approach is convenient only when you know what flags does the command accepts. Moreoever, this is a one-time activity for each project, so I don't think that verbose prompts will anyway interfere with the development rhythm of the project.
