### ISSUE TITLE
grunt-modernizr is really slow

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator-webapp_DEPRECATED#150]
It currently takes 3s on a fast machine, which is a 1/3 of the whole build time.

```
build                                              395ms
concurrent:dist                                    3s
autoprefixer:dist                                  118ms
requirejs:dist                                     798ms
cssmin:dist/styles/main.css                        35ms
uglify:dist/scripts/vendor/modernizr.js            159ms
uglify:dist/scripts/vendor.js                      1s
uglify:dist/scripts/main.js                        1s
uglify:dist/bower_components/requirejs/require.js  164ms
modernizr                                          3s
usemin:html                                        37ms
usemin:css                                         11ms
Total                                              10s
```

Testcase: https://dl.dropboxusercontent.com/u/71884/grunt-modernizr-testcase.zip (just run `npm install && bower install`)

// @doctyper

**Comment by doctyper** [comment]
Hm. Not sure why that's happening. Running `grunt modernizr` in your demo builds in a much shorter time. I also noticed a ~2s difference between first-run and subsequent build calls.

I will say that grunt-modernizr does not do well with minified files. It takes much longer to crawl a minified file than an expanded file. Maybe that's an issue?

**Comment by robwierzbowski** [comment]
Sounds like a good hypothesis. IMO it's safest to run tasks that need to parse code before minification (like https://github.com/yeoman/grunt-usemin/issues/44#issuecomment-18016684).

**Comment by sindresorhus** [comment]
> I will say that grunt-modernizr does not do well with minified files. It takes much longer to crawl a minified file than an expanded file. Maybe that's an issue?

Why is that?

## 

Just tried targeting the source files instead and still running at 3s.

**Comment by sindresorhus** [comment]
ping

**Comment by addyosmani** [comment]
Would it be possible for us to run some experiments testing out that hypothesis? I feel like it would be useful to (in general) know if we should be avoiding ops post minification.

**Comment by eddiemonge** [comment]
related? https://github.com/yeoman/generator-webapp/issues/190

**Comment by addyosmani** [comment]
It is related. Should we move this to being run before minification as suggested?

**Comment by doctyper** [comment]
So I just landed some [RegExp tweaks](https://github.com/Modernizr/grunt-modernizr/commit/f96d498b9ab38d0137d90ccd1e1bd38c30decabd) in an effort to boost performance. I'm getting some pretty big gains in overall compile time with the results.

The bottleneck seems to be that [minimatch](https://github.com/isaacs/minimatch) performs non-negated file lookups first, then filters out the negated paths. Thus in my case, each project's `node_modules` directory was being crawled and indexed. This considerably slowed down performance depending on the amount of modules and/or CSS and JS files per directory. It's probably why I was getting such varied reports about performance.

I ended up using RegExp to negate the `node_modules` directory inline. I am seeing a 50-60% improvement in speed due to the tweak.

Please feel free to test the change and report the results. I'm eager to see if the boost isn't just my imagination. You'll have to install `grunt-modernizr` via the develop branch:

``` shell
npm install grunt-modernizr@https://github.com/Modernizr/grunt-modernizr/tarball/develop --save-dev
```

Also note that I've converted `grunt-modernizr` into a multi-task, so you'll have to tweak your Gruntfile:

``` js
modernizr: {
  dist: {
    devFile: '',
    outputFile: '',
    // etc
  }
}
```

@addyosmani Yes, there are some definite speed issues parsing minified files. The plugin splits each file on a line break and pattern matches each line. Longer lines take longer to parse, and minified file line lengths tend to be massive.

/cc @sindresorhus @eddiemonge

**Comment by addyosmani** [comment]
@doctyper thanks once again for reporting back here. I believe that around the time you posted your response we investigated the development branch to see how well it worked. I was wondering if there had been further work done since to land those changes in master or if the changes are still considered a WIP.

**Comment by doctyper** [comment]
The changes are stable and ready to go. I was waiting for more feedback before pulling the trigger. It should land in master today.

**Comment by doctyper** [comment]
@addyosmani `grunt-modernizr@0.5.0` has been published to [npm](https://npmjs.org/package/grunt-modernizr).

**Comment by silvenon** [comment]
grunt-modernizr takes less than 500ms since #323, this can be closed. @addyosmani @sindresorhus

**Comment by addyosmani** [comment]
Thanks for the update @silvenon!

**Comment by sindresorhus** [comment]
That's still pretty slow though... But at least better than before.
