### ISSUE TITLE
Include LESS Bootstrap

### ISSUE THREAD

**Issue by say2joe** [yeoman/generator-webapp_DEPRECATED#160]
I'm a bit surprised that the default bootstrap is SASS in the default (webapp) generator. Considering the default Bootstrap (v2.3) comes in a LESS flavor, wouldn't it make more sense for that to be a default? Regardless, LESS should absolutely be an option (though I do like the SASS flavor, it is not the default for Bootstrap).

**Comment by addyosmani** [comment]
generator-webapp is by design an opinionated solution, which is one of the reasons why it's opted for Sass over less. I completely understand why you would want to use LESS or something else instead however. 

What I can say is that it's unlikely that -webapp is going to get support for LESS Bootstrap in the short-term, but we are going to make it much easier for other generators (e.g a generator-less-bootstrap) to be used with our existing generators. This is a more long-term thing.

Another solution is of course just forking and customizing with less yourself :) 

@sindresorhus is it worth us better documenting this? We've been asked about this quite frequently lately.

**Comment by say2joe** [comment]
Thanks for the reply... and, I understand your reasoning. SASS is a better
solution in my opinion as well.

Joe Johnson
657-464-HTML

**Comment by say2joe** [comment]
Looks like someone beat me to the proverbial punch. There's 2 new bootstrap-less generators since I opened this issue. Now, I feel bad for not creating one myself (been real busy with work).
