### ISSUE TITLE
Feat: Customize Directory Paths

### ISSUE THREAD

**Issue by changalberto** [yeoman/generator-webapp_DEPRECATED#182]
Can we add customization to where our assets should live in the prompt?

Out of the box I include HTML5 Boilerplate and jQuery.
[?] What more would you like? (Press <space> to select)
❯⬢ Bootstrap for Sass
 ⬢ RequireJS
 ⬢ Modernizr
 ⬢ Customize Directory

Sometimes like to have:
- app
  - assets
    - css
    - img
    - js
      - vendor
    - sass
  - components

Would be really awesome if it asked me:

Where are your bower components?
a: "compenents" default: "bower_components"

Your Javascript directory (default: "scripts"):
custom: "assets/js"

Your styles directory default: "styles":
custom: "assets/css"

etc....

**Comment by pankajparashar-zz** [comment]
I like this idea! But I wonder this will bloat-up the installation script.

**Comment by robwierzbowski** [comment]
Generator-jekyllrb does this. It's more complicated, but only as much as it has to be.

**Comment by markedup** [comment]
I also prefer to work with /css, /img, /js and /sass as well, so this would be a helpful addition.

I've tried hacking the generated files to do this after the fact, and it's not simple!

**Comment by addyosmani** [comment]
If I remember correctly, one of the very first versions of yeoman supported directory customization. It was removed because we felt it led to overly verbose prompts.

I'm not opposed to something like this being available, but it would probably have to be behind either a `--verbose` flag or another prompt that lets you customize target directories for things.

**Comment by addyosmani** [comment]
cc @sindresorhus

**Comment by sindresorhus** [comment]
@addyosmani ya, not only overly verbose prompts but it complicates with minimal gain. I think our structure has become pretty sane. `scripts` for JS or any other preprocessor, `styles` for CSS or any preprocessor, and `bower_components` for vendor components of various kinds. When you use a generator you subscribe to it's best practises, if you don't agree you could easily fork or create your own. But do try to not fall into the trap of forcing every tool to fit your workflow instead of adopting best practises from that workflow.

That being said it could happen when we implement the learning prompt thingy so it's not asked every time, but instead remember the previous choices. But I still don't see the point and few has asked us for it. Let's keep this open for now to see if there's more interest in this.

**Comment by silvenon** [comment]
I agree with @addyosmani and @sindresorhus, `scripts` and `styles` are great directory names because they are language-agnostic. Having a `sass` directory would make things unnecessarily inconvenient if you end up using LESS for some reason. Not only this, but having `scripts` and `styles` directories can save you time when you're modifying configuration, which is not rare in the land of Grunt.  

I would make a PR for this, activated by the `--verbose` flag, but this would introduce unnecessary complexity to the already complex Gruntfile.

**Comment by robwierzbowski** [comment]
There's a fine line between opinionation making project setup easier (less config) and making it harder (a group of devs has an established structure they follow, less config === edit many files after scaffolding). Directory prompts added minimal complexity to generator-jekyllrb, and allows easier config for more use cases / new users. And defaults are set so you can always just tap return through everything.

With composable generators I feel like it's a better pattern to specify `<%= dir.css %>`, `<%= dir.js %>`, `<%= dir.coffee %>`, etc., than to use an expected-standardized string. IMO configurable-during-scaffolding dirs are a solid win.

**Comment by silvenon** [comment]
Let's establish pros and cons by going through as many possible situations.

The one that's coming to my mind at the moment is:

``` coffee
superAwesomeTask:
  dist:
    options:
      awesomeOption: true
    files: [
       expand: true
       cwd: '<%= config.app %>'
       src: 'coffee/{,*/}*.coffee'
       dest: '.tmp/'
    ]
```

In this case you can't use `<%= config.coffeeDir %>` or whatever the variable would be named. Assuming the content of `config.coffeeDir` would be something like `<%= config.app %>/coffee`.

In my opinion, any edge case where you can't use the variable is making them pointless.

**Comment by changalberto** [comment]
I agree that we shouldn't make this project more complex than already is (this is to not start a sort of ideology debate). But I think that we can at least improve on the configuration conventions in grunt a bit. For instance, as @robwierzbowski mentions:

## Current:

```
    // Project settings
    config: {
        // Configurable paths
        app: 'app',
        dist: 'dist'
    }
```

---

```
        js: {
            files: ['<%= config.app %>/scripts/{,*/}*.js'],
            tasks: ['jshint'],
            options: {
                livereload: true
            }
        }
```

Be can probably improve this to:

```
    // Project settings
    config: {
        // Configurable paths
        app: {
                       js: 'app/scripts/{,*/}*.js'
                    },
        dist: 'dist'
    }
```

---

```
        js: {
            files: ['<%= config.app.js %>],
            tasks: ['jshint'],
            options: {
                livereload: true
            }
        }
```

Alternatively, we can probably do a .yoconfig file where we can setup all the paths and have grunt pull from there?

Having a .yoconfig file at the root of the project can double as an indicator that the project uses yeoman?

**Comment by silvenon** [comment]
In my opinion having `config` is pointless as well, because you can change these paths with a simple search and replace, plus it's shorter to type the actual value. (`<%= config.app %>` vs. `app`)

Having stuff like `app: { js: 'app/scripts/{,*/}*.js' }` would disable users from using `<%= config.app %>` by itself.

**Comment by robwierzbowski** [comment]
@silvenon I don't see any reason you couldn't use config.coffeeDir there. You just can't (nor should you) combine app and asset dir -- you need to be able to do `app/scripts` and `dist/scripts`, or `app/js` and `dist/js`.

I agree we should take out the config entirely. Switching app / dist directory is rarely used. But, I don't  use a config var in generator-jekyllrb, I just template in the dir names during generation.

This does work. Download and run the jekyll generator and see how it works. It's pretty easy.

**Comment by silvenon** [comment]
Yeah, I used it a couple of times, it is easy indeed. And I don't mind extra questions in the beginning, because you only do them once per project and I don't start new projects that often :smiley: 

Oh, I misunderstood what you meant for `config.coffeeDir` to contain. Still, I prefer preprocessor-agnostic folder names. The few times I would have to change the directory names, I can do a simple search & replace. I don't really see having a `coffee` or `sass` directory as something that's often a strict requirement, because `styles` and `scripts` are superior.

I guess in the end it's pretty much a matter of taste.

**Comment by robwierzbowski** [comment]
I think it's more about having styles vs CSS vs assets/stylesheets, etc.
People have their own patterns they like to follow, especially I it's an
existing application they're moving into Yeoman.

On Friday, March 21, 2014, Matija Marohnić notifications@github.com wrote:

> Yeah, I used it a couple of times, it is easy indeed. And I don't mind
> extra questions in the beginning, because you only do them once per project
> and I don't start new projects that often [image: :smiley:]
> 
> Oh, I misunderstood what you meant for config.coffeeDir to contain.
> Still, I prefer preprocessor-agnostic folder names. The few times I would
> have to change the directory names, I can do a simple search & replace. I
> don't really see having a coffee or sass directory as something that's
> often a strict requirement, because styles and scripts are superior.
> 
> I guess in the end it's pretty much a matter of taste.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yeoman/generator-webapp/issues/182#issuecomment-38270457
> .

## 

Rob Wierzbowski
@robwierzbowski http://twitter.com/#!/robwierzbowski
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by robwierzbowski** [comment]
I don't think find/replace is a great solution. What if there's a config
property called stylesheets (I believe compass has one) or javascripts?

On Friday, March 21, 2014, Rob Wierzbowski rob.wierzbowski@gmail.com
wrote:

> I think it's more about having styles vs CSS vs assets/stylesheets, etc.
> People have their own patterns they like to follow, especially I it's an
> existing application they're moving into Yeoman.
> 
> On Friday, March 21, 2014, Matija Marohnić <notifications@github.com<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Yeah, I used it a couple of times, it is easy indeed. And I don't mind
> > extra questions in the beginning, because you only do them once per project
> > and I don't start new projects that often [image: :smiley:]
> > 
> > Oh, I misunderstood what you meant for config.coffeeDir to contain.
> > Still, I prefer preprocessor-agnostic folder names. The few times I would
> > have to change the directory names, I can do a simple search & replace. I
> > don't really see having a coffee or sass directory as something that's
> > often a strict requirement, because styles and scripts are superior.
> > 
> > I guess in the end it's pretty much a matter of taste.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/yeoman/generator-webapp/issues/182#issuecomment-38270457
> > .
> 
> ## 
> 
> Rob Wierzbowski
> @robwierzbowski http://twitter.com/#!/robwierzbowski
> http://github.com/robwierzbowski
> http://robwierzbowski.com

## 

Rob Wierzbowski
@robwierzbowski http://twitter.com/#!/robwierzbowski
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by silvenon** [comment]
It's risky to just blindly search & replace everything, you should execute it in a way that it asks for confirmation for each occurrence. It shouldn't take more than 2 minutes.

**Comment by eddiemonge** [comment]
The current strategy I'm exploring for this very topic in the Angular generator is to use a yo-rc.json file to store the config for these. The config block can have the defaults and then if you want to override that, you specify it in the yo-rc.json file. Instead of having tons of prompts, advanced users who know they want to change these things can preconstruct (maybe we could even have a generator to do it) the yo-rc.json file and then put in the folder, run this generator and the generator will install things according to the json file.

**Comment by robwierzbowski** [comment]
I like the idea of specifying in a yo-rc file (why wasn't it named .yorc, out of curiosity?), and letting those be defaults for prompts. We've talked a couple times about hiding some prompts behind a flag (super quick and opinionated generation with `--skipconfig` or some such vs. more configurable generation). 

Wading through a file piece by piece would certainly work, but we could do that with config too. Basically I see this as a simple addition that doesn't complicate the final Gruntfile (no editable config after generation) but does help users set up a project based on their own specifications, which has the potential to increase adoption. I guess it depends on how opinionated Yeoman wants to be.

**Comment by changalberto** [comment]
This sounds like a good idea!

**Comment by changalberto** [comment]
I agree that .yorc sounds like a better naming convention. It is more inline with what the rest of the front end tools' conventions where no dashes are used or camel casing.

**Comment by sygint** [comment]
I am working on implementing this, I'd love to get some feedback on how you think we should handle the prompt for the custom file (i was thinking by a flag "--custom" or something)

**Comment by sygint** [comment]
I am almost completely done with this implementation, but there is a problem with the 'connect' task under livereload:options:middleware:

```
connect.static('<%%= config.tmp %>'),
connect().use('/bower_components', connect.static('./bower_components')),
connect.static(config.app)
```

the original config works, but mine doesn't:

```
connect.static('<%%= config.tmp %>'),
connect().use('/<%%= config.components %>', connect.static('./<%%= config.components %>')),
connect.static('<%%= config.app %>')
```

Is this not how I should be doing it? because it DOES work like this:

```
connect.static(config.tmp),
connect().use('/' + config.components, connect.static('./' + config.components)),
connect.static(config.app)
```

my fork/branch: https://github.com/gnarmedia/generator-webapp/tree/yoConfig

**Comment by sygint** [comment]
https://github.com/gnarmedia/generator-webapp/tree/custom-directories

it might need some more testing, maybe someone can help me out

**Comment by sindresorhus** [comment]
Closing as this repo is deprecated.
