### ISSUE TITLE
Not automatically compiling when making changes to Bootstrap itself?

### ISSUE THREAD

**Issue by hansrodtang** [yeoman/generator-webapp_DEPRECATED#194]
Not sure where to add this, but I was wondering if Compass (in its default setup) not watching changes to bootstrap.scss and its imported files is a bug or if it is intentional? 

Since it is in the importPath and is imported like all other files I would assume it did, but it does not seem to work that way, or am I mistaken?

I know updating Bootstrap itself is not best practice for updates and so on, just wondering why it does not work.

**Comment by pppdns** [comment]
IMHO you shouldn't edit bootstrap's files or any libraries themselves but instead write the overrides in your own stylesheets that extend it. If bower-imported components and 3rd party libs were also watched for changes I'm sure that would introduce quite much performance overhead

**Comment by eddiemonge** [comment]
It should be reloading when changes to /app/styles/main.scss is edited. is that not the case?

**Comment by hansrodtang** [comment]
It does update when editing main.scss, but adding and removing spaces each time I want to get nitty-gritty with Bootstrap itself is tedious. If this is not officially supported, can anyone point me to how I should go forth to make this happen in my own installation?

**Comment by addyosmani** [comment]
It is just changes to spaces that are causing this or generic changes that aren't causing the recompilation?

**Comment by robwierzbowski** [comment]
@hansrodtang Are you editing Bootstrap in bower_components?

Bower components are like npm modules or gems: they're meant to be overridden, not edited. If you run `bower update` you'll overwrite all of your changes.

If you want to edit bootstrap directly (which is perfectly valid) you need to remove it from bower.json and move the files into your css/sass/less directory. It ceases to be a component managed by bower and just becomes part of your application.

As an aside, we can't watch the bower_component directory for changes because many packages include entire repos, not just the built components ( :| ), so we quickly reach the OS based limit on files that can be watched simultaneously.

**Comment by eddiemonge** [comment]
@hansrodtang are you editing the bower installed files? Can you please elaborate or close the ticket if you think its not necessary anymore?

**Comment by eddiemonge** [comment]
@hansrodtang Can this be closed?

**Comment by hansrodtang** [comment]
Yes, closing it, even though I would like a feature like this it seems out of the scope of the project or something more suitable for a separate issue.
