### ISSUE TITLE
Increment version number

### ISSUE THREAD

**Issue by amckinlay** [yeoman/generator-webapp_DEPRECATED#202]
The latest published version has an indentation bug that causes the default Grunt task to fail.

```
$ grunt
Running "jshint:all" (jshint) task

Gruntfile.js
  line 315  col 7  Expected 'grunt' to have an indentation at 9 instead at 7.
  line 316  col 7  Expected 'grunt' to have an indentation at 9 instead at 7.

✖ 2 problems

Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.

Elapsed time
loading tasks  1s
jshint:all     63ms
Total          1s
```

This was fixed with 4e8704ad0e9ca376c59478cac3ae883e0ab8c357.

**Comment by eddiemonge** [comment]
the next release should be published in the near future

**Comment by ravitadi** [comment]
is it fixed?

**Comment by tao-hpu** [comment]
i got same error too.

**Comment by tao-hpu** [comment]
i think just:

```
grunt.registerTask('server', function () {
  //grunt.log.warn('The `server` task has been deprecated. Use `grunt serve` to start a server.');
  //grunt.task.run(['serve']);
});
```

**Comment by addyosmani** [comment]
Note: this issue is currently on our stable version on npm meaning that there currently does not exist a version of generator-webapp users can rely on today that actually works when you run `grunt` after a scaffold. We need to fix this.

With Modernizr currently breaking our builds on master, we either need to rectify those issues or push an interim version to npm with these indendation issues corrected. 

```
Running "jshint:all" (jshint) task

Gruntfile.js
  line 315  col 7  Expected 'grunt' to have an indentation at 9 instead at 7.
  line 316  col 7  Expected 'grunt' to have an indentation at 9 instead at 7.

✖ 2 problems

Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.
```
