### ISSUE TITLE
Build is moving styles to the wrong path

### ISSUE THREAD

**Issue by oskarrough** [yeoman/generator-webapp_DEPRECATED#204]
Just did `npm update -g` and now the default generator-webapp is moving main.css to `dist/.tmp/styles/main.css` on build. Can't wrap my head around what changed.

Running generator-webapp 0.4.4 with node v0.10.22 on OSX 10.9. Here's the [Gruntfile.js](http://www.pastebay.net/1355775) and [build log](http://www.pastebay.net/1355772).

**Comment by Khrystyna** [comment]
I got the same issue with the fresh install of webapp generator.

**Comment by haydenbleasel** [comment]
I have an error related to this I think. I believe this is a similar issue, if it helps: https://github.com/yeoman/yeoman/issues/411

**Comment by eddiemonge** [comment]
can you gist the output of the `grunt build` process?

**Comment by eddiemonge** [comment]
i think it might be related to https://github.com/yeoman/grunt-usemin/issues/238

**Comment by haydenbleasel** [comment]
@eddiemonge - First gist is `grunt`, outputs the following which was fixed in https://github.com/yeoman/generator-webapp/pull/192, second gist is `grunt build` (or `grunt` after fixing indentation problems).

https://gist.github.com/haydenbleasel/7539859

Problem for me is here:

```
Running "cssmin:generated" (cssmin) task
>> Destination not written because minified CSS was empty.
```

Generated with Modernizr and Bootstrap for Sass on Mac OSX 10.9, latest `yo` and `generator-webapp`.

**Comment by eddiemonge** [comment]
@oskarrough @Khrystyna @haydenbleasel can you try updating usemin and try again?

**Comment by haydenbleasel** [comment]
@eddiemonge - Updated to `2.0.2`. No dice I'm afraid, same error as my previous comment.

**Comment by smongey** [comment]
@haydenbleasel I was having a very similar issue. In your gruntfile uncomment the dist section for cssmin and it should do the trick although the names of the images referenced in you css don’t get revved.

**Comment by smongey** [comment]
@haydenbleasel Actually just sussed it will revv them if its url('/images/logo.png') not if its url(../images/logo.png)

**Comment by haydenbleasel** [comment]
@smongey - For reference, this error happens without any modifications to the scaffold i.e. just running `yo webapp` then `grunt build`.

**Comment by oskarrough** [comment]
The webapp is now working out of the box again. Also tried updating usemin from 2.0.0 to 2.0.2 and both were working.

@haydenbleasel could you try `npm update -g` and see it if works now?

**Comment by haydenbleasel** [comment]
@oskarrough - Did an `npm update -g` and generated a new webapp with `yo webapp`, still produces the same error. Not sure why that would have changed, [usemin](https://npmjs.org/package/grunt-usemin) hasn't been updated in a week, [generator-webapp](https://npmjs.org/package/generator-webapp) hasn't been updated in 3 weeks. Since your error was different and it's now apparently resolved, we can bring this over to #211.

**Comment by oskarrough** [comment]
Sure.

**Comment by ecurtis** [comment]
I am getting this same error. I have updated gems, npm and brew with not luck.

A fresh install of webapp and an immediate grunt build gives me:

Running "cssmin:generated" (cssmin) task

> > Destination not written because minified CSS was empty.
> > File dist/styles/main.css created.

OS X 10.9.1
