### ISSUE TITLE
Bootstrap plugins usage

### ISSUE THREAD

**Issue by haydenbleasel** [yeoman/generator-webapp_DEPRECATED#239]
As discussed in [this issue](https://github.com/yeoman/generator-webapp/pull/238), we could either:

a) drop the plugins
b) move them to their own prompt

We should ask on Twitter if anyone uses the plugins while scaffolding to decide.

CC: @addyosmani @sindresorhus @passy

**Comment by addyosmani** [comment]
My vote is to drop them outright and advise that they can be installed via Bower (which I believe is the case). We can definitely help tweet out the question for more votes.

**Comment by sindresorhus** [comment]
Mine too. And because of `bower-install` it's easy enough to have it automatically added to the index.html if the bower package is correct.

**Comment by haydenbleasel** [comment]
@addyosmani - You mentioned before that we should keep Bootstrap in the prompt because:

> When you're starting a new project, especially during prototyping, having a set of default styles out of the box can be pretty powerful.

I'm concerned that users (mostly new users) may opt to install Bootstrap and be confused as to why there's no Bootstrap JS included pre-emptively. Having carousels and dropdowns out of the box is just as handy for prototyping as navbars and hero units.

**Comment by eddiemonge** [comment]
+1 to drop with documentation on how to install: `bower install bootstrap --save-dev; grunt bower-install`

**Comment by addyosmani** [comment]
That's a fair point @haydenbleasel. I'll tweet this out and see if we can get some more opinions about it on the thread :)

**Comment by qmx** [comment]
drop

**Comment by pr3ssh** [comment]
a)

**Comment by hotmeteor** [comment]
+1 drop

**Comment by kmmathis** [comment]
I don't see anything wrong with disabling them by default but adding an option to add them in if needed.

**Comment by tbassetto** [comment]
I agree with @haydenbleasel. When I used this generator the first time I was expecting the plugins to be included with Bootstrap styles => I consider `Bootstrap` to be the whole thing. And I guess that's the case for a lot of users too.

Maybe it would make more sense to include Bootstrap plugins only if you select `Bootstrap` first (the styles, Less or Sass flavour)?

**Comment by emagnier** [comment]
a) drop the plugins for me too

**Comment by Tobino** [comment]
Imho a) drop

**Comment by nsteinmetz** [comment]
+1 for drop as I use Foundation instead of bootstrap

**Comment by eddiemonge** [comment]
Might make sense to just have a small CSS subset so the project has some styles and example of css best practices. (s/css/scss/g if the user chooses sass instead of css).

Also, we could put the documentation on how to add a framework to the example project itself.

**Comment by haydenbleasel** [comment]
I just can't see the logic in dropping the Bootstrap JS components. They're not affecting the build in any dramatic way, and removing them just creates a flaw in the Yeoman prompt logic.

As @tbassetto pointed out, when users select Bootstrap, they're opting for the full Bootstrap (CSS and JS). Selecting to include Bootstrap, only receiving half the package and being forced to use bower-install to load the JS seems strange.

Realistically, we should be serving users a scaffold that they can develop with and prune at a later state. I tend to install a bunch of Bower components and reference the compiled CSS / JS files in the head. When I'm ready to deploy, I prune each package by referencing particular source files and removing unused code.

Since we're serving the full CSS Bootstrap package initially, we might as well serve the full JS as well to make prototyping and development easier, and users can prune the components later when they're ready to deploy.

**Comment by furstenberg** [comment]
I agree with @haydenbleasel.

**Comment by addyosmani** [comment]
Some revised thoughts. We can either:
- Move Bootstrap plugins into their own prompt (satisfies those that want it and those that don't)
- Continue including them as is
- Drop them

A lot of the votes on here suggest dropping would be preferred, but we shouldn't be making things more difficult for users that do want to use the plugins. 

Will keep this open a little longer to get more opinions before we make a call.

**Comment by sndrs** [comment]
I'm with @haydenbleasel. If you instruct the prompt to install bootstrap, I think you would reasonably expect the full style and widget libraries to be installed, since that's what 'bootstrap' is (not just a preferred subset). 

(I think it's worth bearing in mind that bootstrap is designed to get you going quickly. If you're opting to include it, shouldn't you be expecting to pare it back for production anyway?)

That said, if the js libraries seem to be overkill, perhaps the prompt could be changed to 'bootstrap styles' or something like that, so there's no confusion?

**Comment by eddiemonge** [comment]
To be clear, my vote is to drop bootstrap altogether, css and plugins.

**Comment by haydenbleasel** [comment]
The most utilitarian option here is to reconfigure the prompt, however it still seems illogical to me:

```
[] Sass with Compass
[] Bootstrap (styles)
[] Bootstrap (scripts)
[] Modernizr
```

I say **styles** and **scripts** rather than **CSS** and **JS** since the style language is dependant on the first option.

@eddiemonge and @nsteinmetz - As pointed out in [this issue](https://github.com/yeoman/generator-webapp/issues/237) by @sindresorhus, Yeoman is meant to be an opinionated starting point for creating web apps, hence the initialisation with Bootstrap rather than a clean slate, and Sass rather than Less.

@addyosmani - Perhaps rather than dropping the plugins from the scaffold, we endorse a library pruning strategy for the Yeoman workflow as discussed in my last comment?

**Comment by addyosmani** [comment]
I'm always going to be of the opinion that we should provide default styling and a CSS library with breakpoints out of the box. I'm the one that suggested we start looking at a pruning strategy, but we need to be very careful with dropping the utilitarian bits of what are scaffolded otherwise this basically becomes HTML5 Boilerplate + some Grunt tasks. 

I'm revising my vote to say let's just continue including the scripts and styles. Whilst it's one more step to remove them, it's likely a better long-term idea than forcing one more prompt upon our users (not that we're opposed to that, but it should be for a much better reason than this).

**Comment by silvenon** [comment]
Using Foundation shouldn't be an argument for dropping Bootstrap plugins, because the generator doesn't support Foundation. Are you guys planning to support it in the future?

I've been using this generator a lot and this Bootstrap setup is perfect for me. I can include and exclude plugins easily or remove them altogether if I don't need them.

Some people like Bootstrap, some don't. The team should choose whether they want it or not, because including it only partially is confusing, as well as providing an additional option for something that could be easily done manually.

**Comment by silvenon** [comment]
@addyosmani What is the conclusion of this discussion? Can we close it in favor of keeping the plugins?

**Comment by eddiemonge** [comment]
I think once we make the bootstrap generator composable, we can remove them from here

**Comment by ZaLiTHkA** [comment]
I was about to raise this in a new issue, but this already has a number of opinions on the matter anyway, so here makes more sense.

Why are the individual Bootstrap plugins (`affix.js`, `alert,js`, etc..) being included in the `index.html`? They all exist in the `dist/js/bootstrap.js` files already, which is loaded directly before them. Seems a tad redundant to me..

[ed] Just a quick note: removing the individual plugin `<script>` tags, even with keeping the `<!-- build.js(.) -->` reference, then running `grunt wiredep` does _not_ add them again, they're only inserted during <a target="_blank" href="https://github.com/yeoman/generator-webapp/blob/master/app/index.js#L132">the initial scaffolding</a>.

**Comment by silvenon** [comment]
The chances are you won't need most of those plugins, so excluding the ones you don't need can make your scripts lighter. They are not managed by wiredep, that's why `grunt wiredep` won't work for them, `bootstrap.js` is specifically excluded [here](https://github.com/yeoman/generator-webapp/blob/master/app/templates/Gruntfile.js#L241-L242) line so they can be managed manually, which is faster than having to manage them in the Gruntfile. Also, `<!--- build -->` blocks are used by usemin, `<!-- bower -->` blocks are the ones used by wiredep.

**Comment by haydenbleasel** [comment]
@ZaLiTHkA Scripts are generally included separately to help isolate errors to specific components. @eddiemonge Has work on a composable Bootstrap been started? I presume it'd be something like [Grunt-Modernizr](https://github.com/Modernizr/grunt-modernizr). Perhaps I can help out with this.

**Comment by ZaLiTHkA** [comment]
@silvenon , @haydenbleasel , thanks for the info. Must admit I understand wiredep much better now than I did at my previous comment (haven't checked this for a while), guess it's just a curious habit of wanting to work out how things work. :)

**Comment by HughxDev** [comment]
How do I exclude the Bootstrap plugins I don't need? Every time I delete them from index.html, running `grunt` erases whatever I put in there and adds them back in along with jquery.

**Comment by silvenon** [comment]
Please open a new issue, this is not related to the discussion.

**Comment by StfBauer** [comment]
Drop the support of bootstrap please..

**Comment by haydenbleasel** [comment]
This issue is really trivial and has dragged on forever. @addyosmani @sindresorhus Perhaps we can just make a decision and close this issue?
