### ISSUE TITLE
missing Mocha run() call

### ISSUE THREAD

**Issue by SciutoAlex** [yeoman/generator-webapp_DEPRECATED#348]
I'm new to yeoman, and I followed the five minute tutorial from YouTube that is linked on the Yeoman website to try it out. I got the `grunt server` up and running, but when I try just `grunt`, I get the error:

<pre>Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.

Aborted due to warnings.</pre>

I've seen a few other tickets about this problem, but none of them seem to apply to someone starting out.

![image](https://cloud.githubusercontent.com/assets/1485679/2822996/adb16784-cf19-11e3-91b3-56ba46b1136a.png)

**Comment by eddiemonge** [comment]
can you run `yo` and list what versions are installed?

**Comment by SciutoAlex** [comment]
<pre>
Alexs-MacBook-Pro-6:grassroots alex$ yo -v
1.1.2
</pre>

**Comment by eddiemonge** [comment]
I mean just run `yo` not `yo -v`

**Comment by SciutoAlex** [comment]
Oh sorry! Does this help?

<pre>
Alexs-MacBook-Pro-6:grassroots alex$ yo
[?] What would you like to do? (Use arrow keys)
❯ Run the Webapp generator (0.4.9) 
  Run the Mocha generator (0.1.3) 
  Update your generators 
  Install a generator 
  Find some help 
  Get me out of here! 
</pre>

**Comment by eddiemonge** [comment]
If you run it multiple times does it still fail?

**Comment by SciutoAlex** [comment]
Yes it does.

**Comment by eddiemonge** [comment]
I don't know. Try these steps:

```
npm rebuild -g
npm rebuild # in your projects folder
grunt test
```

**Comment by FunTimeCoding** [comment]
I tried this `npm rebuild` it didn't fix my issue. #347
and `nom up` and `npm up -g`, my `yo` is 1.1.2 and the output it shows when typing `yo` in the project is just slightly different:

```
[?] What would you like to do? (Use arrow keys)
❯ Run the Angular generator (0.8.0)
  Run the Webapp generator (0.4.9)
  Run the Karma generator (0.7.0)
  Run the Mocha generator (0.1.3)
  Update your generators
  Install a generator
  Find some help
  Get me out of here!
```

**Comment by SciutoAlex** [comment]
This might be related?
<pre>
....
grunt-sass@0.11.0 node_modules/grunt-sass
├── each-async@0.1.3
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
└── node-sass@0.8.6 (node-watch@0.3.4, mkdirp@0.3.5, nan@0.8.0, optimist@0.6.1, mocha@1.18.2, sinon@1.9.1)

module.js:340
    throw err;
    ^
Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-mocha/node_modules/yeoman-generator/node_modules/findup-sync/lib/findup-sync.js:15:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Alexs-MacBook-Pro-6:cmugrassroots.us alex$ grunt

**Comment by FunTimeCoding** [comment]
possibly. it seems like a missing module causes an error in mocha - yes?

**Comment by SciutoAlex** [comment]
I'm out of my depth here, sorry. I'm not sure what is going on at all with this error.

**Comment by SciutoAlex** [comment]
Sorry another piece that may help. I was trying to install http-server using npm. It gave me errors some of which involved yeoman. I updated node using homebrew, then updated the npm packages. Don't know if that made any difference.
![screen shot 2014-05-11 at 8 54 31 pm](https://cloud.githubusercontent.com/assets/1485679/2940250/7610358a-d978-11e3-9e60-d749cdfb3ef3.png)

**Comment by eddiemonge** [comment]
https://github.com/yeoman/generator-webapp/issues/349#issuecomment-46579496

**Comment by eddiemonge** [comment]
If this is still happening let us know

**Comment by vzmaru** [comment]
Go to test folder and run `bower install`. It worked for me.

$ cd test/
$ bower install
...
$ cd ..
$ grunt

**Comment by LubomirGeorgiev** [comment]
@vzmaru Is right. It fixes the issue. :+1:

**Comment by bernov** [comment]
@vzmaru Good Job! bower install in test folder fixes issue!

**Comment by yogibear54** [comment]
@vzmaru Thanks!  This fixed my problem as well!

**Comment by joeczucha** [comment]
Same here, great work vzmaru :)

**Comment by resting** [comment]
I got the same problem. @vzmaru solution works.

**Comment by narayanwaraich** [comment]
@vzmaru Works for me as well.

**Comment by jaywilburn** [comment]
Perfect fix. Thanks @vzmaru!

**Comment by YarGnawh** [comment]
@vzmaru simple fix. thanks!   surprised it isn't ran automatically or informed to the user.

**Comment by tmarrs** [comment]
OK, why is this considered closed? We have to run an extra step (bower install in the test directory).
I still consider this an open issue because someone new to this generator would have to look here.
Shouldn't the webapp generator automatically install the dependencies for the tests? OR could you please document this extra step in README.md? That way, it just works without getting errors.

**Comment by eddiemonge** [comment]
Its currently a bug in generator-mocha that we are working out.

**Comment by Techdoode** [comment]
@eddiemonge  Interesting.  Where is the bug being tracked?  I just want to follow so I'll know when it's fixed.

**Comment by bonyboy** [comment]
I have run `bower install` in the test dir followed by `grunt` and still getting the same PhamtomJS error.

**Comment by silvenon** [comment]
You can track yeoman/generator-mocha#28, that's the approach we ultimately want to implement.

**Comment by wfresch** [comment]
But, you can't run bower install until you resolve these errrors, right?
- No bower.json present
- git is not installed or not in the PATH

**Comment by silvenon** [comment]
What do you mean? You should have a `test/bower.json` and git should be installed and available in your PATH.

**Comment by skullmasher** [comment]
vzmaru solution has worked for me thanks.

```
Go to test folder and run bower install. It worked for me.

$ cd test/
$ bower install
...
$ cd ..
$ grunt
```

**Comment by eddiemonge** [comment]
This seems fixed for me. I tried with a fresh environment and generation and it installed bc in the test folder.

**Comment by ragingwind** [comment]
It worked for me.

**Comment by bartgryszko** [comment]
I had similar problem on my Mac as described here: https://github.com/yeoman/generator-chrome-extension/issues/43#issuecomment-58410268, running `sudo xcodebuild -license` resolved the problem.

**Comment by ptitgraig** [comment]
@vzmaru that worked for me as well. Thanks.

**Comment by ssteinerx** [comment]
I'm working on a new machine that didn't have node, npm, mocha, or bower installed (not to mention a zillion things on my usual machine.  

Installing all of the above still gives this error:

Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.

Aborted due to warnings.

It seems to me that there is an unspoken dependency here that "everyone" who does node.js development has installed on their machines, but whatever it is, it's not on my machine and there's no indication of what to do to fix it...

UPDATE: I just ran 

```
  # grunt server
```

Which got me:

Running "wiredep:app" (wiredep) task
Cannot find where you keep your Bower packages.

So I ran:

```
  # bower install
```

After installing bower, mocha et al., and am now able to run the app with:

```
  # grunt server
```

But `grunt` by itself still fails with the same error.

UPDATE2:

By running `bower install` again in the test directory, `grunt` by itself will now run.

So...

bower and mocha are not installed by this generator, but must be present to successfully run the gruntfile and bower must be run in both the root and test directories before `grunt` will run in the root.

**Comment by silvenon** [comment]
As rare a case it may be, perhaps we should note that you need to have Bower installed globally in the docs (because we can't do it for them).

You don't have to install Mocha manually, generator-webapp installs it for you, as well as other dependencies. Did you somehow skip the step of installing dependencies?

Concerning running `bower install` in the `test` directory, I'm sorry that you had to waste time figuring that out yourself :worried: This is a known issue and the fix was already been pointed out in the comments (https://github.com/yeoman/generator-webapp/issues/348#issuecomment-51100659).

We're planning to add deps from `test/bower.json` to `bower.json` as `devDependencies`, so that we can remove `test/bower.json`, as outlined [here](https://github.com/yeoman/generator-mocha/issues/28).

**Comment by ssteinerx** [comment]
I'm not sure how rare this would be as anyone setting up a new VM (with puppet/salt/ansible/chef etc.) would need to be aware of the dependency.  This was the first (and only) thing I had installed on this new machine that required bower.  That said, everything else was a working meteor app and had nothing to do with yeoman at all.

I don't know whether Bower must be installed globally;  might it be able to be used locally?  That would mean that it could install locally if it's not found.

You are correct, Mocha was installed by generator-webapp.  I installed it globally manually in an attempt to address what appeared to be the cause of the error message.

As for `bower install` in the test directory, I had tried to apply the noted fix, but `bower` wasn't installed at all.  

Once that was fixed, I hadn't remembered to run it in the test directory causing the main `grunt` invocation to fail.  

I was pointing it out more in a summary form; as soon as I remembered that it had not been run in the test directory, I did it.  I was more noting this to document the sequencing of failures (and solutions) than anything else.

**Comment by silvenon** [comment]
Thanks for the valuable feedback, our docs aren't clear enough about that.

**Comment by rienierpatron** [comment]
hi guys, Im trying to create a webapp and when I run yo webapp Im getting this error
![untitled](https://cloud.githubusercontent.com/assets/4182684/6281907/a940189a-b905-11e4-9617-ff0f1389ccf8.png)
 I hope that you could help me with this guys..thanks

**Comment by silvenon** [comment]
This doesn't appear to be related to this issue, please open a new one.

**Comment by eddiemonge** [comment]
@rienierpatron Try running npm install again

**Comment by robr24** [comment]
npm install -g chalk

**Comment by arthurvr** [comment]
@robr24 globally installing it does not make any sense in here.

**Comment by eddiemonge** [comment]
There is too much noise in this thread with no new reports of this happening. Closing this and if it still happens please open a new issue.

**Comment by robr24** [comment]
If it's missing chalk, then installing chalk will solve the issue.

**Comment by eddiemonge** [comment]
If chalk is the only thing missing. But there is no need to globally install a module when its a dependency of a project. `npm install` will install it locally. Generally the only time a global module is needed is if its a command line module, and even then its not always necessary to globally install.

**Comment by robr24** [comment]
That's correct. Thank you.
