### ISSUE TITLE
Grunt: Was `wiredep` changed to `bowerInstall`?

### ISSUE THREAD

**Issue by ChrisAntaki** [yeoman/generator-webapp_DEPRECATED#394]
The documentation speaks of using `grunt wiredep`, to wire up Bower dependencies. This task seems to have been replaced with `grunt bowerInstall`, in the Gruntfile.

However, when `grunt bowerInstall` is executed, Bootstrap's JS ends up in the `vendor.js` block, even though the `plugins.js` block still has individualized scripts for different Bootstrap plugins.

Just a heads up. Great work on this generator.

**Comment by ChrisAntaki** [comment]
Note: This might relate to #239

**Comment by silvenon** [comment]
Thanks for the heads up :) `bowerInstall` has been renamed to `wiredep` in 3ae2eb1439850d7cbad39ed6410945402816ce97 (the plugin name was updated from grunt-bower-install to grunt-wiredep). That version wasn't released yet, but the documentation follows the latest stuff, that's why you're confused.

The second issue should be solved with:

``` diff
-exclude: ['bower_components/bootstrap-sass-official/vendor/assets/javascripts/bootstrap.js']
+exclude: ['bower_components/bootstrap-sass-official/vendor/assets/javascripts']
```

in your Gruntfile. After that try running `grunt bowerInstall` again, let me know if that works.

**Comment by ChrisAntaki** [comment]
Oh, thanks @silvenon !
