### ISSUE TITLE
autoprefixer config set to ie 11, but browsehappy set to ie 10

### ISSUE THREAD

**Issue by gregz67** [yeoman/generator-webapp_DEPRECATED#397]
I love autoprefixer (#62), but the default config for `last 1 version` limits support to ie 11.  However, the 'browsehappy' conditional comment in index.html is set to `[if lt IE 10]`.  This presents two problems:
- app will not display 'browsehappy' for ie 10 but does not have necessary prefixes for ie 10.  presents broken css, but no warning.
- dev using the generator can be misled by 'browsehappy' code if they are not aware that autoprefixer is configured.  they think ie 10 is supported, but prefixes will be missing.

**Comment by KingScooty** [comment]
Yeah, this bugs me too, i recently discovered a bunch of IE and Firefox issues in a project that were purely issues because autoprefixer decided to skip generating the necessary IE and Firefox prefixes. 

The whole reason to use autoprefixer is to support the older browsers, so we should be using some sensible defaults. You'll want to use the following:
(I'll open a pull request in a second)

``` javascript
    autoprefixer: {
      options: {
        browsers: ['> 1%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1']
      },
```

**Comment by gregz67** [comment]
Great!
