### ISSUE TITLE
Add some more usage information and "how it works" information to the docs

### ISSUE THREAD

**Issue by nareshbhatia** [yeoman/generator-webapp_DEPRECATED#409]
It is very difficult to figure out best practices for this generator from the docs alone. I am constantly looking at the grunt script to reverse engineer the thinking behind it. For example:
- If I want to add a second js file (in addition to the existing main.js), where should I add it in index.html? Would it go in this section: `<!-- build:js({app,.tmp}) scripts/main.js -->`? If yes, will it be concatenated with main.js?
- If I have a vendor library that is not bower enabled, what's the quickest way to add it to the project? Say it is as simple as one js file and one css file. Is it possible to drop the css file in the styles folder as is, or do I have to change the name to .scss at a minimum?
- What is the distinction between vendor.js and plugins.js section of the index.html file? Why is bootstrap singled out and thrown in to the plugins.js section?
- As for the general workflow, it appears that all js and css processing is targeted to the .tmp folder. This area is used by grunt serve and well as the dist version. This and other "how it works" type of information would be very useful for people using the generator.

**Comment by silvenon** [comment]
I agree, I also think there should be a tutorial, Gruntfiles are very hard to read. I'll get around to it next week.

**Comment by nareshbhatia** [comment]
Can someone please provide some quick answers inline? It will be VERY useful for me.

Thanks.

**Comment by silvenon** [comment]
Oh, sorry, I got the idea that you figured it out.

> If I want to add a second js file (in addition to the existing main.js), where should I add it in index.html? Would it go in this section: ? If yes, will it be concatenated with main.js?

Yes, it should go in that comment block, next to `main.js`. Everything between `build:js` and `endbuild` will be concatenated and compressed when you build the site. Same goes for `build:css`.

> If I have a vendor library that is not bower enabled, what's the quickest way to add it to the project? Say it is as simple as one js file and one css file. Is it possible to drop the css file in the styles folder as is, or do I have to change the name to .scss at a minimum?

Yes, you can simply drop a `.css` in `styles`, but you should also `<link>` it in `index.html`, because Bower-enabled assets get linked automatically. Same goes for `js`.

> What is the distinction between vendor.js and plugins.js section of the index.html file? Why is bootstrap singled out and thrown in to the plugins.js section?

`vendor.js` is generally used for automatically included Bower components, `plugins.js` is used for manually added vendor files. In the future we will probably merge `vendor.js` and `plugins.js`, I currently don't see any reason why they are separated blocks. Bootstrap is separated because you usually don't want to include all components. This way you can include the ones you want and save up file size.

> As for the general workflow, it appears that all js and css processing is targeted to the .tmp folder. This area is used by grunt serve and well as the dist version. This and other "how it works" type of information would be very useful for people using the generator.

Yes, `.tmp` is an intermediate folder where stuff like `.scss/.sass` and `.coffee` files are compiled to and then either served or built.

You don't have to use the generator as a black box, reading the Gruntfile in order to understand how it works is a good thing.

**Comment by nareshbhatia** [comment]
Thanks so much for the clarifications, @silvenon. I agree that the generator should not be treated as a black box. I have learned so much about grunt and it's plugins by reading the gruntfile. My main reason for creating this issue is to make it easier for newbies to get started and not "drop out" due to the initial bumps. Also there are times when it is simply not possible to get into the generator's mind and figure out why things were done the way they were. This is very clear from your useful comments above!

Thanks again!

**Comment by Samirbekaert** [comment]
+1 for helpfulness

**Comment by eddiemonge** [comment]
This is for angular but its the same theory http://yeoman.io/codelab.html
