### ISSUE TITLE
Bower install plugin not work in build

### ISSUE THREAD

**Issue by nithinM** [yeoman/generator-webapp_DEPRECATED#464]
Hi,
I have face some few issues and I need to know how I fix those issue. I listed them in bellow.
1. Some bower install plugin not add css file path to the html file. 
ex:
I am trying to install jquery.uniform using bower and it added js file path to the html file but css file not added. Then I added the path manually in to the html file under "" and when server start or build command run that path automatically remove. If I add that path after that "" it work only for the app server, not in the build.
1. Most of the time bower install plugin images not loaded. 
   ex:
   I am install select2 using bower. It nicely added css and js file to html file. Build also included it. But in the build image not loaded. 

Thanks!!

**Comment by silvenon** [comment]
There are 2 issues here:
1. Uniform most probably doesn't have their `main` field in `bower.json` properly specified, i.e. they didn't include CSS files. You can override this in your `bower.json`, read more about that in wiredep's [documentation](https://github.com/taptapship/wiredep#bower-overrides).
2. Images are not automatically copied to your build, you need to manually copy those to your project and adjust paths to those images in Uniform's CSS accordingly.

Uniform seems like one of those dependencies where installing via Bower is not worth it. I suggest just downloading and including the assets yourself.

Also, because this is not really an issue with this generator, I'm closing it.
