### ISSUE TITLE
Watching bootstrap files (sass)

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp_DEPRECATED#469]
This may be a stupid question, how do I make the app watch for changes to the bootstrap files ?

For example if I change a variable in bootstrap i would expect this to recompile and reload the page with the changes 

Can anyone help ?

**Comment by silvenon** [comment]
You shouldn't modify anything in your `bower_components` folder, because those are external dependencies outside source control, so your team wouldn't get your changes. You can make a `_variables.scss` file where you override some of Bootstrap's variables and import it in `main.scss` **before** importing Bootstrap. Your `_variables.scss` will automatically be watched your styles will be recompiled.

Let me know if I understood your question correctly.

**Comment by silvenon** [comment]
By the way, these questions are best asked on Stack Overflow, because it's not an issue with this generator.

**Comment by ghost** [comment]
Thanks for that, and apologies for asking on here
