### ISSUE TITLE
sass:server error 

### ISSUE THREAD

**Issue by mirkojovanovic** [yeoman/generator-webapp_DEPRECATED#499]
When i try to run grunt:serve i get this output. 

```
C:\xampp\htdocs\portfolio>grunt serve
Running "serve" task

Running "clean:server" (clean) task
>> 1 path cleaned.

Running "wiredep:app" (wiredep) task

modernizr was not injected in your file.
Please go take a look in "C:\xampp\htdocs\portfolio\bower_components\modernizr"for the file you need, then manually include it in your file.

Running "wiredep:sass" (wiredep) task

modernizr was not injected in your file.
Please go take a look in "C:\xampp\htdocs\portfolio\bower_components\modernizr"for the file you need, then manually include it in your file.

Running "concurrent:server" (concurrent) task
Warning: Running "sass:server" (sass) task Use --force to continue.

Aborted due to warnings.


Execution Time (2015-01-25 12:30:18 UTC)
loading tasks       3.2s  ███████████████████ 43%
wiredep:app        345ms  ██ 5%
concurrent:server   3.9s  ███████████████████████ 52%
Total 7.4s
```

I tried updating sass (and all other gems), changing npm version was 2.3.0 now it's 2.0.2, <code>bower cache clean</code> and <code>npm install</code>. What can cause this issue? My OS is Win 8.1.

**Comment by dniccum** [comment]
I am seeing the same thing.

**Comment by silvenon** [comment]
Your `wiredep` task is also failing, which is weird. Does all of this happen on a fresh install?

**Comment by mirkojovanovic** [comment]
No it worked great previously. I don't know what it can be, i didn't touched Gruntfile. I added a path for modernizer but it doesn't change things.

 In fact i think this first happened when i updated sass to latest version. I wasn't able to install with <code>-g</code> so i navigated to nodejs folder and installed sass locally. Maybe this caused problem. What do you think?

**Comment by eddiemonge** [comment]
it looks like its failing on the modernizr part.

**Comment by silvenon** [comment]
I don't think that `wiredep` task is what's causing the `serve` task to fail, it's just a warning. I need more information. Rather than asking you to send over the `Gruntfile.js`, `index.html`, `bower.json` etc., could you maybe send a link to your repo if it's not top secret? Or a ZIP version? Just so I can run it myself.

**Comment by mirkojovanovic** [comment]
https://www.dropbox.com/s/gnjfx66vvslzmhb/portfolio.zip?dl=0

**Comment by silvenon** [comment]
To fix the `modernizr` task fail, you should reinstall Modernizr:

``` sh
$ rm -r bower_components/modernizr
$ bower install
```

You somehow deleted `modernizr.js` from that directory, that's why the task can't find it.

To fix the `sass:server` task, you should first update grunt-sass:

``` sh
npm install --save-dev grunt-sass
```

Now your Sass error messages will be more useful:

```
Warning: /Users/matija/Downloads/portfolio/app/styles/main.scss:4: file to import not found or unreadable: '_helpers'
Current dir: /Users/matija/Downloads/portfolio/app/styles/
```

Your `app/styles/main.scss` contains:

``` scss
// bower:scss
// endbower

@import '_helpers';
```

Which doesn't exist. For some reason your project contains both `app/styles` and `styles` directories. I'm guessing you want to replace `app/styles` with `styles`, because `styles` is more developed. I'm sure you can pick it up from there :wink: 

I'll close this as this is not an issue with our generator.

**Comment by mirkojovanovic** [comment]
Thank you so much. It was hard to live without your generator!

**Comment by brunowego** [comment]
Thanks @silvenon :+1:

**Comment by volocake** [comment]
Thank you @silvenon! :+1:

**Comment by rowild** [comment]
Thanks so much for the this, @silvenon !!!

**Comment by vedovato** [comment]
Wow, thank you so muck @silvenon saved my life and prevented me from throwing my computer ......
