### ISSUE TITLE
grunt serve overwrites code in index.html

### ISSUE THREAD

**Issue by amboy00** [yeoman/generator-webapp_DEPRECATED#557]
Hi, folks. On `grunt serve`,  all of the scripts I have between these vendor tags get reset.

``` html
<!-- build:js(.) scripts/vendor.js -->
<!-- bower:js -->
<script src="bower_components/jquery/dist/jquery.js"></script>
<!-- endbower -->
<!-- endbuild -->
```

So every time, I need to manually add the other scripts back into it.

``` html
<!-- build:js(.) scripts/vendor.js -->
<!-- bower:js -->
<script src="bower_components/jquery/dist/jquery.js"></script>
<script src="my-other-framework.js"></script>
<script src="bower_components/knockout/dist/knockout.js"></script>
<!-- endbower -->
<!-- endbuild -->
```

It took me a while to figure out what may be affecting this.  If I list the items in _bower.json_, then they stay, if I do not, they get removed.

**Comment by silvenon** [comment]
Hey :smiley: We are using [wiredep](https://github.com/taptapship/wiredep) for injecting dependencies between the `bower`/`endbower` comments. The dependencies **have** to be listed in `bower.json`, otherwise wiredep won't know about them. So you should install every dependency with `bower install --save <dependency>`. The point of that is that you won't have to inject those manually, and you shouldn't, because everything between those comments will get overwritten as soon as the `wiredep` task is called.

We should really document this here, but [here](https://github.com/yeoman/generator-gulp-webapp/tree/master/docs#bower) are the docs from our generator-gulp-webapp, where we're using the same tool.

**Comment by amboy00** [comment]
Ah, I see. This seems new from how I'm used to using it.  Is there a way to include dependencies not available in Bower?

**Comment by silvenon** [comment]
Just include them outside the comment block.

This is not supposed to be limiting, it just offers an automatic injection so you would only have to do `bower install --save jquery` while `grunt serve` is running, which automatically fires up `grunt wiredep` and injects jQuery in your HTML. You could also download jQuery yourself and include it manually outside the comment block.

**Comment by silvenon** [comment]
> This seems new from how I'm used to using it.

Using what, in particular?

**Comment by amboy00** [comment]
Previous versions of this generator.

**Comment by silvenon** [comment]
Oh. Yeah, judging by the `(.)` in your comment blocks, I'd say you've been using an ancient version. That's our fault, we should release versions more often. In the meantime I suggest just using the master version (using `npm link`).
