### ISSUE TITLE
UNMET DEPENDENCY

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp_DEPRECATED#559]
when i run sudo npm install -g generator-webapp, it shows below

npm WARN peerDependencies The peer dependency yo@>=1.2.0 included from generator-webapp will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency generator-mocha@>=0.1.0 included from generator-webapp will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'

after it installed , i run npm ls in dir generator-webapp, it shows 

npm ERR! missing: generator-karma@>=0.9.0, required by generator-angular@0.11.1
npm ERR! missing: yo@>=1.0.0, required by generator-angular@0.11.1

how could i solve this problem
my os is ubuntu, and versions node --version && npm --version && yo --version are
v0.12.4
2.10.1
1.4.7

thanks

**Comment by silvenon** [comment]
`generator-webapp` being the cloned instance of this repo? It doesn't make much sense, because it's throwing on generator-angular, which is a different project.

I used to have these, but after reinstalling node and npm they disappeared. Try doing the same. I suggest using [nvm](https://github.com/creationix/nvm) for installing node and npm, it makes it very easy.

Let us know how it goes.

**Comment by ghost** [comment]
@silvenon I just rmove node and install all tools again, confirm every step all right. Then, it's ok. Thanks a lot.4

**Comment by silvenon** [comment]
:+1:
