### ISSUE TITLE
Feature: CoffeeScript support

### ISSUE THREAD

**Issue by bryceroney** [yeoman/generator-webapp_DEPRECATED#605]
It would be neat to have an option for those users wishing to use CoffeeScript to compile their JS.

**Comment by silvenon** [comment]
We had CoffeeScript support, but we removed it in favor of [Babel](https://babeljs.io/).

CoffeeScript was created to patch some shortcomings of JavaScript (other than to provide some syntactic sugar). Now that we have an ES2015 transpiler, there's no real need to support CoffeeScript anymore. We generally advise using plain JS over CoffeeScript because it's native (i.e. new features will be faster), the barrier of entry is lower (e.g. Atom being written in CS only [increases the barrier](https://twitter.com/sindresorhus/status/591869731109343233)) and it already has most of CoffeeScript's features, so there is less and less reason for CoffeeScript to exist.

**Comment by eddiemonge** [comment]
Adding CoffeeScript to your generated app is as easy as following the instructions at https://github.com/gruntjs/grunt-contrib-coffee  
You could also always fork the repo and add CoffeeScript back if you wanted to.
