### ISSUE TITLE
Feature: React Webapp Generator

### ISSUE THREAD

**Issue by changalberto** [yeoman/generator-webapp_DEPRECATED#606]
@addyosmani @sindresorhus Are there plans to create an official Yeoman React WebApp Generator that offers scaffolding options such as Flux, Redux, Reflux?

**Comment by silvenon** [comment]
None of the [existing](http://yeoman.io/generators/) React generators fits your needs? I maintain [generator-wbp](https://github.com/silvenon/generator-wbp) which has React. It doesn't have the options you listed, though.

Closing this because it's not an issue. These questions are best asked on Twitter or Freenode.
