### ISSUE TITLE
concat target doesn't consolidate babel output

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp_DEPRECATED#631]
I use es6 syntax in my main.js file. But `grunt build` command fails because **concat** target doesn't use Babel output.

sample scenario:

```
yo webapp
echo "let a = 45;" >> app/scripts/main.js
grunt build
```

**Comment by silvenon** [comment]
Fails how? This [line](https://github.com/yeoman/generator-webapp/blob/master/app/templates/index.html#L94) is supposed to tell grunt-usemin to look in `.tmp/scripts` (compiled) rather than `app/scripts` (source), so I'm confused as to why it doesn't work. I will try to reproduce this issue, I just wish every fresh `npm install` didn't last half an hour :cry:

**Comment by sindresorhus** [comment]
Closing as this repo is deprecated.
