### ISSUE TITLE
Assemble recipe error

### ISSUE THREAD

**Issue by marikunt** [yeoman/generator-webapp_DEPRECATED#634]
If I follow the instructions in the recipe I get an error that assemble isn´t installed.
Then I have installed the "grunt-assemble" and now I get this error:

Running "assemble:pages" (assemble) task
handlebars does not support render.
Assembling .tmp/index.html ERROR
Warning: handlebars does not support render

Can you update the recipe please?

**Comment by miniplus** [comment]
@marikunt the `assemble` package has been completely rewritten so it seems. You are correct to use `grunt-assemble` instead.

The error you are getting is because of an underlying dependency being wrong. Both a cause and possible solution is explained [here](https://github.com/assemble/handlebars-helpers/issues/199#issuecomment-151970480).

It should be fixed there instead. 

Referencing the issue: assemble/handlebars-helpers#199

**Comment by sindresorhus** [comment]
Closing as this repo is deprecated.
