### ISSUE TITLE
Add receipes to yeoman generator

### ISSUE THREAD

**Issue by upgreydd** [yeoman/generator-webapp_DEPRECATED#635]
Please add all receipes to generator. It would be nice to generate whole project without rewriting it using receipes.

**Comment by silvenon** [comment]
If I understood you correctly, you want us to implement all recipes into the generator?

**Comment by upgreydd** [comment]
That would be nice, but this is only feature. Every time I use these generator I'm changing sass to less and html to jade. In my opinion selectable options when generating project would be nicer ;)

Don't get me wrong, that's a proposition only.

**Comment by silvenon** [comment]
Unfortunately we can't do this, that's why we added recipes in the first place.

We added Sass because it's the most popular choice and changing it to another preprocessor should be easy.

We also got a number of requests to implement Jade or some other templating language, but because there are so many of them and there's no clear winner (depends on your framework, it could be Handlebars, JSX etc.), we decided to stick with HTML. We mentioned it in the [FAQ](https://github.com/yeoman/generator-gulp-webapp/blob/master/docs/faq.md#could-you-add-templating-engine-x).

You could maintain your own fork of this generator with these features included.
