### ISSUE TITLE
Unused bootstrap.js

### ISSUE THREAD

**Issue by iokill** [yeoman/generator-webapp_DEPRECATED#93]
What is the purpose of `app/scripts/vendor/bootstrap.js`? As far as I see it this files is never used, since `app/index.html` only references the JS files of boostrap in `bower_components/sass-bootstrap`.

**Comment by addyosmani** [comment]
This is actually a bug. It shouldn't be there afaik.

Related: @passy @sindresorhus Looking at: https://github.com/yeoman/generator-webapp/blob/master/app/index.js#L156
we appear to try including the Bootstrap plugins if you've opted into Compass but not RequireJS. If this is the case, we then go and include the following in your index file:

```
        <!-- build:js scripts/plugins.js -->
        <script src="bower_components/sass-bootstrap/js/bootstrap-affix.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-alert.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-dropdown.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-tooltip.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-modal.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-transition.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-button.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-popover.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-typeahead.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-carousel.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-scrollspy.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-collapse.js"></script>
        <script src="bower_components/sass-bootstrap/js/bootstrap-tab.js"></script>
        <!-- endbuild -->
```

This feels weird because the user hasn't explicitly opted in to using these plugins, just Sass Bootstrap. Is it generally considered that if you're using Sass-Bootstrap you would get these plugins included just like that?

@apfelsaft if no one disagrees, I'll drop bootstrap.js from being copied over. Afaik, it was left over from a time when we weren't installing Bootstrap from Bower.

**Comment by iokill** [comment]
Ok, that's what I thought. :)

As for the Bootstrap plugins:
From my experience, most of the time you'd probably want the plugins to be included. So IMHO it's ok to add these includes to the index file. Otherwise it we could explicitly ask the user if the plugins should be included (in case `!includeRequireJS`).
