### ISSUE TITLE
generator-webapp@0.2.4 : autoprefixer issue

### ISSUE THREAD

**Issue by fcamblor** [yeoman/generator-webapp_DEPRECATED#94]
Seems like there is an issue with the `autoprefixer` task in `package.json` :

```
Loading "autoprefixer.js" tasks...ERROR
>> Error: Cannot find module 'autoprefixer'
```

I had to remove the following line from `package.json` to fix this :

```
    "grunt-autoprefixer": "~0.1.20130516",
```

(note that I answered `no` to the `Would you like to use autoprefixer for your CSS?` yeoman question)

**Comment by passy** [comment]
As a quick fix, could you try and see if `grunt-autoprefixer` is listed in your `package.json` as `devDependency` and if so remove it?

This seems to be a problem with `autoprefixer` being a `peerDependency` of `grunt-autoprefixer`. It looks like sometimes npm fails to install this.

**Comment by fcamblor** [comment]
Removing `grunt-autoprefixer` in package.json fixes the problem (as I stated in my initial post ;-))

**Comment by passy** [comment]
D'oh, that comment was before my first coffee today. ;)

**Comment by passy** [comment]
`grunt-autoprefixer` is no longer loaded through matchdep from now on, when it's disabled. However, I still don't understand why the peer dependency installation fails sometimes. Could you tell me what `npm --version` prints for you?

**Comment by fcamblor** [comment]
Sorry for the bad latency :-)

```
$> npm --version
1.1.62
$> node --version
v0.8.11
```

**Comment by addyosmani** [comment]
@passy with the change for grunt-autoprefixer no longer being loaded through matchdep, is this still occasionally failing? I ask as I believe this is one of the two issues we're waiting on before we can cut a new release.

**Comment by passy** [comment]
@addyosmani We narrowed this down to obsolete npm versions. So this can only happen if you manually enable autoprefixer in the prompt and run a version of npm from before 1.2.10 or so. @sindresorhus suggested we should add an engine requirement to the generator for npm `~1.3.0` so that there is at least a warning if you're running an incompatible version.

**Comment by addyosmani** [comment]
> @sindresorhus suggested we should add an engine requirement to the generator for npm ~1.3.0 so that there is at least a warning if you're running an incompatible version.

SGTM.

**Comment by passy** [comment]
"Fixed" by #100

**Comment by YonasBerhe** [comment]
I'm having issues when trying to run the grunt server command. 

yonas@yonas:~/Documents/code/vailroom/listingpage$ grunt serve
Running "serve" task

Running "clean:server" (clean) task

> > 1 path cleaned.

Running "wiredep:app" (wiredep) task

Running "concurrent:server" (concurrent) task

```
Running "copy:styles" (copy) task
Copied 1 files

Done, without errors.


Execution Time (2014-12-30 03:19:10 UTC)
loading tasks  1.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 1.8s
```

Running "autoprefixer:dist" (autoprefixer) task
Warning: .tmp/styles/main.css:60:1: Unexpected } Use --force to continue.

Aborted due to warnings.

Execution Time (2014-12-30 03:19:08 UTC)
loading tasks       1.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 43%
wiredep:app        122ms  ▇▇ 3%
concurrent:server   2.1s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 52%
autoprefixer:dist   53ms  ▇ 1%
Total 4s

yonas@yonas:~/Documents/code/vailroom/listingpage$

**Comment by silvenon** [comment]
It isn't related to this issue, raised as #494.
